const USER_CARDS_LIST_ADD = "USER_CARDS_LIST_ADD";
const USER_CARDS_LIST_REMOVE = "USER_CARDS_LIST_REMOVE";
const USER_LIST_SEARCH = "USER_LIST_SEARCH";
const SORTER_AND_FILTER_USER_CARDS_LIST_SET = "SORTER_AND_FILTER_USER_CARDS_LIST_SET";
const BD_SEARCH = "BD_SEARCH";
const BD_LIST_SET = "BD_LIST_SET";
const BD_LIST_ADD = "BD_LIST_ADD";
const BD_LIST_REMOVE = "BD_LIST_REMOVE";
const MODAL_BD_WINDOW_TOGGLE = "MODAL_BD_WINDOW_TOGGLE";

export {
    USER_CARDS_LIST_ADD, 
    USER_CARDS_LIST_REMOVE, 
    USER_LIST_SEARCH, 
    SORTER_AND_FILTER_USER_CARDS_LIST_SET,
    BD_SEARCH,
    BD_LIST_SET,
    BD_LIST_ADD,
    BD_LIST_REMOVE,
    MODAL_BD_WINDOW_TOGGLE
};

